### ISSUE TITLE
Tradebase - Create live market table

### ISSUE THREAD

**Issue by Spook3D** [Jay1987/TradeCraft#18]

**Comment by Spook3D** [comment]
table design, based on info from getmarketsummaries.  

exchange

exchange_id
exchange_market_id
exchange_last
exchange_ask
exchange_bid
exchange_high
exchange_low
exchange_base_volume
exchange_volume
exchange_timestamp

**Comment by Jay1987** [comment]
Renamed table to market_price. Kept the same column structure.

Complete.
