### ISSUE TITLE
Tradebase - Create market table

### ISSUE THREAD

**Issue by Spook3D** [Jay1987/TradeCraft#28]

**Comment by Spook3D** [comment]
Created this issue retrospectively for comments.

I think we would benefit from holding the market_name in this table.

The requests to populate the live market(Exchange table) and a lot of other requests seem to return market name, therefore having it in the table would allow us to get the market_id easier or even just use the market_name as a foreign key.

**Comment by Jay1987** [comment]
I can't add a market name column. It would break normalisation to have it hard coded.
